version: '3.1'
services:
  bot:
    build:
      context: .
      dockerfile: ./bot/bot.Dockerfile
    user: root
    depends_on:
      - actions
      - db
    ports:
      - 5005:5005
    volumes:
      - ./bot:/app

  actions:
    build:
      context: .
      dockerfile: ./bot/actions.Dockerfile
    ports:
      - 5055:5055
      
  sci:
    build:
      context: .
      dockerfile: ./sistema-de-controle-de-informacoes-ifrs/sci.Dockerfile
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./sistema-de-controle-de-informacoes-ifrs:/sci

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ifrs
    ports:
      - 5432:5432
    
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080