version: '3.1'
services:
  bot:
    build:
      context: .
      dockerfile: ./bot/bot.Dockerfile
    user: root
    depends_on:
      - actions
      - db
      - sci
    ports:
      - 5005:5005
    volumes:
      - ./bot:/app
    networks: 
      - rasa-network

  actions:
    build:
      context: .
      dockerfile: ./bot/actions.Dockerfile
    ports:
      - 5055:443
    networks: 
      - rasa-network
      
  sci:
    build:
      context: .
      dockerfile: ./sistema-de-controle-de-informacoes-ifrs/sci.Dockerfile
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./sistema-de-controle-de-informacoes-ifrs:/sci
    networks: 
      - rasa-network

  db:
    image: postgres
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    networks: 
      - rasa-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ifrs
    
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks: 
      - rasa-network

networks: 
  rasa-network:
      driver: bridge